config/routes.rb
Rails.application.routes.draw do
  get 'tasks',          to: 'tasks#index', as: 'index'

  get 'tasks/new',      to: 'tasks#new', as:'create'


  get 'tasks/:id',      to: 'tasks#show', as: 'task'
  post 'tasks',         to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch 'tasks/:id',    to: 'tasks#update', as: 'update'

  delete 'tasks/:id',   to: 'tasks#destroy', as:'destroy'

  root to: 'tasks#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to index_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

   <%= form_for(@task) do |f| %>
      <%= f.text_field :name %>
      <%= f.submit %>
      <%= f.text_field :description %>
      <%= f.submit %>

    <% end %>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>


  <div class="card">
    <div class="card-category"> <%= @task.status%> </div>
    <div class="card-description">
      <h2><%= f.text_field :name %></h2>
      <p><%= f.text_area(:description, size: '50x5') %></p>
      <div class="edit-button">
        <button class="btn btn-outline-success btn-sm">Edit!</button>
      </div>
    </div>
  </div

<% end %>

app/views/tasks/index.html.erb
<div class="container">
  <h2>Here is your Task List!</h2>
   <button type="button"  class="btn btn-outline-success btn-sm"><%= link_to "Add new Task!", create_path(@tasks) %></button>
  <% @tasks.each do |t| %>
    <div class="row">
      <div class="col-xm-12 col-md-12 col-lg-12">
        <ul class="list-group">
          <li class="list-group-item">
            <%= "#{t.name}   " %>
              <div class="buttons">
                <button type="button"  class="btn btn-outline-success btn-sm"><%= link_to "Details", task_path(t) %></button>
                <button type="button"  class="btn btn-outline-success btn-sm"><%= link_to "Edit me!", edit_path(t) %></button>
                <button type="button"  class="btn btn-outline-success btn-sm"><%= link_to "Delete me!", destroy_path(t), method: :delete %></button>
            </div>
          </li>
        </ul>
      </div>
    </div>
  <%end%>
</div>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>


  <div class="card">
    <div class="card-category"> <%= @task.status%> </div>
    <div class="card-description">
      <p>Name: <%= f.text_field :name %></p>
      <p><%= f.text_area(:description, size: '50x5') %></p>
      <div class="edit-button">
        <button class="btn  btn-outline-success btn-sm">Add!</button>
      </div>
    </div>
  </div

<% end %>

app/views/tasks/show.html.erb
<div class="card">
  <div class="card-category"> <%= @task.status%> </div>
  <div class="card-description">
    <h2><%= " #{@task.name}"%> </h2>
    <p><%= @task.description%> </p>
    <div class="task-buttons">
      <button type="button"  class="btn btn-outline-success btn-sm"><%= link_to "Edit me!", edit_path(@task) %></button>
      <button type="button"  class="btn btn-outline-success btn-sm"><%= link_to "Delete me!", destroy_path(@task), method: :delete %></button>
      <button type="button"  class="btn btn-outline-success btn-sm"><%= link_to "Back", index_path(@task) %></button>
    </div>
  </div>
</div>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>